version: '3.8'

services:
  music-visualizer:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_APP=app_simple.py
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
